type Era = {
  name: string;
  ruby: string;
  rubyInitial: string;
  year: number;
  month: number;
  day: number;
};

export const eras: Array<Era> = [
  { name: "白雉", ruby: "はくち", rubyInitial: "H", year: 650, month: 2, day: 15 },
  {
    name: "朱鳥",
    ruby: "しゅちょう（すちょう）",
    rubyInitial: "S",
    year: 686,
    month: 7,
    day: 20,
  },
  {
    name: "大宝",
    ruby: "たいほう（だいほう）",
    rubyInitial: "T",
    year: 701,
    month: 3,
    day: 21,
  },
  {
    name: "慶雲",
    ruby: "けいうん（きょううん）",
    rubyInitial: "K",
    year: 704,
    month: 5,
    day: 10,
  },
  { name: "和銅", ruby: "わどう", rubyInitial: "W", year: 708, month: 1, day: 11 },
  { name: "養老", ruby: "ようろう", rubyInitial: "Y", year: 717, month: 11, day: 17 },
  { name: "神亀", ruby: "じんき", rubyInitial: "J", year: 724, month: 2, day: 4 },
  {
    name: "天平",
    ruby: "てんぴょう（てんびょう）",
    rubyInitial: "T",
    year: 729,
    month: 8,
    day: 5,
  },
  {
    name: "天平感宝",
    ruby: "てんぴょうかんぽう",
    rubyInitial: "T",
    year: 749,
    month: 4,
    day: 14,
  },
  {
    name: "天平勝宝",
    ruby: "てんぴょうしょうほう",
    rubyInitial: "T",
    year: 749,
    month: 7,
    day: 2,
  },
  {
    name: "天平宝字",
    ruby: "てんぴょうほうじ",
    rubyInitial: "T",
    year: 757,
    month: 8,
    day: 18,
  },
  {
    name: "天平神護",
    ruby: "てんぴょうしんご",
    rubyInitial: "T",
    year: 765,
    month: 1,
    day: 7,
  },
  {
    name: "神護景雲",
    ruby: "しんごけいうん",
    rubyInitial: "S",
    year: 767,
    month: 8,
    day: 16,
  },
  { name: "宝亀", ruby: "ほうき", rubyInitial: "H", year: 770, month: 10, day: 1 },
  { name: "天応", ruby: "てんおう", rubyInitial: "T", year: 781, month: 1, day: 1 },
  { name: "延暦", ruby: "えんりゃく", rubyInitial: "E", year: 782, month: 8, day: 19 },
  { name: "弘仁", ruby: "こうにん", rubyInitial: "K", year: 810, month: 9, day: 19 },
  { name: "天長", ruby: "てんちょう", rubyInitial: "T", year: 824, month: 1, day: 5 },
  {
    name: "承和",
    ruby: "じょうわ（しょうわ）",
    rubyInitial: "J",
    year: 834,
    month: 1,
    day: 3,
  },
  {
    name: "嘉祥",
    ruby: "かしょう（かじょう）",
    rubyInitial: "K",
    year: 848,
    month: 6,
    day: 13,
  },
  { name: "仁寿", ruby: "にんじゅ", rubyInitial: "N", year: 851, month: 4, day: 28 },
  { name: "斎衡", ruby: "さいこう", rubyInitial: "S", year: 854, month: 11, day: 30 },
  {
    name: "天安",
    ruby: "てんあん（てんなん）",
    rubyInitial: "T",
    year: 857,
    month: 2,
    day: 21,
  },
  { name: "貞観", ruby: "じょうがん", rubyInitial: "J", year: 859, month: 4, day: 15 },
  {
    name: "元慶",
    ruby: "がんぎょう（げんけい）",
    rubyInitial: "G",
    year: 877,
    month: 4,
    day: 16,
  },
  {
    name: "仁和",
    ruby: "にんな（じんな）",
    rubyInitial: "N",
    year: 885,
    month: 2,
    day: 21,
  },
  {
    name: "寛平",
    ruby: "かんぴょう（かんぺい）",
    rubyInitial: "K",
    year: 889,
    month: 4,
    day: 27,
  },
  { name: "昌泰", ruby: "しょうたい", rubyInitial: "S", year: 898, month: 4, day: 26 },
  { name: "延喜", ruby: "えんぎ", rubyInitial: "E", year: 901, month: 7, day: 15 },
  { name: "延長", ruby: "えんちょう", rubyInitial: "E", year: 923, month: 4, day: 11 },
  {
    name: "承平",
    ruby: "じょうへい（しょうへい）",
    rubyInitial: "J",
    year: 931,
    month: 4,
    day: 26,
  },
  {
    name: "天慶",
    ruby: "てんぎょう（てんきょう）",
    rubyInitial: "T",
    year: 938,
    month: 5,
    day: 22,
  },
  {
    name: "天暦",
    ruby: "てんりゃく（てんれき）",
    rubyInitial: "T",
    year: 947,
    month: 4,
    day: 22,
  },
  { name: "天徳", ruby: "てんとく", rubyInitial: "T", year: 957, month: 10, day: 27 },
  { name: "応和", ruby: "おうわ", rubyInitial: "O", year: 961, month: 2, day: 16 },
  { name: "康保", ruby: "こうほう", rubyInitial: "K", year: 964, month: 7, day: 10 },
  {
    name: "安和",
    ruby: "あんな（あんわ）",
    rubyInitial: "A",
    year: 968,
    month: 8,
    day: 13,
  },
  { name: "天禄", ruby: "てんろく", rubyInitial: "T", year: 970, month: 3, day: 25 },
  { name: "天延", ruby: "てんえん", rubyInitial: "T", year: 973, month: 12, day: 20 },
  {
    name: "貞元",
    ruby: "じょうげん（ていげん）",
    rubyInitial: "J",
    year: 976,
    month: 7,
    day: 13,
  },
  { name: "天元", ruby: "てんげん", rubyInitial: "T", year: 978, month: 11, day: 29 },
  { name: "永観", ruby: "えいかん", rubyInitial: "E", year: 983, month: 4, day: 15 },
  {
    name: "寛和",
    ruby: "かんな（かんわ）",
    rubyInitial: "K",
    year: 985,
    month: 4,
    day: 27,
  },
  {
    name: "永延",
    ruby: "えいえん（ようえん）",
    rubyInitial: "E",
    year: 987,
    month: 4,
    day: 5,
  },
  { name: "永祚", ruby: "えいそ", rubyInitial: "E", year: 989, month: 8, day: 8 },
  {
    name: "正暦",
    ruby: "しょうりゃく（じょうりゃく）",
    rubyInitial: "S",
    year: 990,
    month: 11,
    day: 7,
  },
  { name: "長徳", ruby: "ちょうとく", rubyInitial: "T", year: 995, month: 2, day: 22 },
  { name: "長保", ruby: "ちょうほう", rubyInitial: "T", year: 999, month: 1, day: 13 },
  { name: "寛弘", ruby: "かんこう", rubyInitial: "K", year: 1004, month: 7, day: 20 },
  {
    name: "長和",
    ruby: "ちょうわ",
    rubyInitial: "T",
    year: 1012,
    month: 12,
    day: 25,
  },
  { name: "寛仁", ruby: "かんにん", rubyInitial: "K", year: 1017, month: 4, day: 23 },
  {
    name: "治安",
    ruby: "じあん（ちあん）",
    rubyInitial: "J",
    year: 1021,
    month: 2,
    day: 2,
  },
  { name: "万寿", ruby: "まんじゅ", rubyInitial: "M", year: 1024, month: 7, day: 13 },
  {
    name: "長元",
    ruby: "ちょうげん",
    rubyInitial: "T",
    year: 1028,
    month: 7,
    day: 25,
  },
  {
    name: "長暦",
    ruby: "ちょうりゃく（ちょうれき）",
    rubyInitial: "T",
    year: 1037,
    month: 4,
    day: 21,
  },
  {
    name: "長久",
    ruby: "ちょうきゅう",
    rubyInitial: "T",
    year: 1040,
    month: 11,
    day: 10,
  },
  {
    name: "寛徳",
    ruby: "かんとく",
    rubyInitial: "K",
    year: 1044,
    month: 11,
    day: 24,
  },
  {
    name: "永承",
    ruby: "えいしょう（えいじょう）",
    rubyInitial: "E",
    year: 1046,
    month: 4,
    day: 14,
  },
  {
    name: "天喜",
    ruby: "てんぎ（てんき）",
    rubyInitial: "T",
    year: 1053,
    month: 1,
    day: 11,
  },
  { name: "康平", ruby: "こうへい", rubyInitial: "K", year: 1058, month: 8, day: 29 },
  {
    name: "治暦",
    ruby: "じりゃく（ちりゃく）",
    rubyInitial: "J",
    year: 1065,
    month: 8,
    day: 2,
  },
  {
    name: "延久",
    ruby: "えんきゅう",
    rubyInitial: "E",
    year: 1069,
    month: 4,
    day: 13,
  },
  {
    name: "承保",
    ruby: "じょうほう（しょうほう）",
    rubyInitial: "J",
    year: 1074,
    month: 8,
    day: 23,
  },
  {
    name: "承暦",
    ruby: "じょうりゃく（しょうりゃく）",
    rubyInitial: "J",
    year: 1077,
    month: 11,
    day: 17,
  },
  { name: "永保", ruby: "えいほう", rubyInitial: "E", year: 1081, month: 2, day: 10 },
  { name: "応徳", ruby: "おうとく", rubyInitial: "O", year: 1084, month: 2, day: 7 },
  { name: "寛治", ruby: "かんじ", rubyInitial: "K", year: 1087, month: 4, day: 7 },
  { name: "嘉保", ruby: "かほう", rubyInitial: "K", year: 1094, month: 12, day: 15 },
  {
    name: "永長",
    ruby: "えいちょう（ようちょう）",
    rubyInitial: "E",
    year: 1096,
    month: 12,
    day: 17,
  },
  {
    name: "承徳",
    ruby: "じょうとく（しょうとく）",
    rubyInitial: "J",
    year: 1097,
    month: 11,
    day: 21,
  },
  { name: "康和", ruby: "こうわ", rubyInitial: "K", year: 1099, month: 8, day: 28 },
  { name: "長治", ruby: "ちょうじ", rubyInitial: "T", year: 1104, month: 2, day: 10 },
  {
    name: "嘉承",
    ruby: "かじょう（かしょう）",
    rubyInitial: "K",
    year: 1106,
    month: 4,
    day: 9,
  },
  { name: "天仁", ruby: "てんにん", rubyInitial: "T", year: 1108, month: 8, day: 3 },
  { name: "天永", ruby: "てんえい", rubyInitial: "T", year: 1110, month: 7, day: 13 },
  {
    name: "永久",
    ruby: "えいきゅう",
    rubyInitial: "E",
    year: 1113,
    month: 7,
    day: 13,
  },
  { name: "元永", ruby: "げんえい", rubyInitial: "G", year: 1118, month: 4, day: 3 },
  { name: "保安", ruby: "ほうあん", rubyInitial: "H", year: 1120, month: 4, day: 10 },
  { name: "天治", ruby: "てんじ", rubyInitial: "T", year: 1124, month: 4, day: 3 },
  {
    name: "大治",
    ruby: "だいじ（たいじ）",
    rubyInitial: "D",
    year: 1126,
    month: 1,
    day: 22,
  },
  {
    name: "天承",
    ruby: "てんしょう（てんじょう）",
    rubyInitial: "T",
    year: 1131,
    month: 1,
    day: 29,
  },
  {
    name: "長承",
    ruby: "ちょうしょう（ちょうじょう）",
    rubyInitial: "T",
    year: 1132,
    month: 8,
    day: 11,
  },
  { name: "保延", ruby: "ほうえん", rubyInitial: "H", year: 1135, month: 4, day: 27 },
  { name: "永治", ruby: "えいじ", rubyInitial: "E", year: 1141, month: 7, day: 10 },
  { name: "康治", ruby: "こうじ", rubyInitial: "K", year: 1142, month: 4, day: 28 },
  { name: "天養", ruby: "てんよう", rubyInitial: "T", year: 1144, month: 2, day: 23 },
  {
    name: "久安",
    ruby: "きゅうあん",
    rubyInitial: "K",
    year: 1145,
    month: 7,
    day: 22,
  },
  {
    name: "仁平",
    ruby: "にんぺい（にんびょう）",
    rubyInitial: "N",
    year: 1151,
    month: 1,
    day: 26,
  },
  {
    name: "久寿",
    ruby: "きゅうじゅ",
    rubyInitial: "K",
    year: 1154,
    month: 10,
    day: 28,
  },
  { name: "保元", ruby: "ほうげん", rubyInitial: "H", year: 1156, month: 4, day: 27 },
  {
    name: "平治",
    ruby: "へいじ（びょうじ）",
    rubyInitial: "H",
    year: 1159,
    month: 4,
    day: 20,
  },
  {
    name: "永暦",
    ruby: "えいりゃく（ようりゃく）",
    rubyInitial: "E",
    year: 1160,
    month: 1,
    day: 10,
  },
  { name: "応保", ruby: "おうほう", rubyInitial: "O", year: 1161, month: 9, day: 4 },
  {
    name: "長寛",
    ruby: "ちょうかん",
    rubyInitial: "T",
    year: 1163,
    month: 3,
    day: 29,
  },
  {
    name: "永万",
    ruby: "えいまん（ようまん）",
    rubyInitial: "E",
    year: 1165,
    month: 6,
    day: 5,
  },
  {
    name: "仁安",
    ruby: "にんあん（にんなん）",
    rubyInitial: "N",
    year: 1166,
    month: 8,
    day: 27,
  },
  { name: "嘉応", ruby: "かおう", rubyInitial: "K", year: 1169, month: 4, day: 8 },
  {
    name: "承安",
    ruby: "じょうあん（しょうあん）",
    rubyInitial: "J",
    year: 1171,
    month: 4,
    day: 21,
  },
  { name: "安元", ruby: "あんげん", rubyInitial: "A", year: 1175, month: 7, day: 28 },
  {
    name: "治承",
    ruby: "じしょう（じじょう）",
    rubyInitial: "J",
    year: 1177,
    month: 8,
    day: 4,
  },
  { name: "養和", ruby: "ようわ", rubyInitial: "Y", year: 1181, month: 7, day: 14 },
  { name: "寿永", ruby: "じゅえい", rubyInitial: "J", year: 1182, month: 5, day: 27 },
  {
    name: "元暦",
    ruby: "げんりゃく",
    rubyInitial: "G",
    year: 1184,
    month: 4,
    day: 16,
  },
  {
    name: "文治",
    ruby: "ぶんじ（もんじ）",
    rubyInitial: "B",
    year: 1185,
    month: 8,
    day: 14,
  },
  { name: "正治", ruby: "しょうじ", rubyInitial: "S", year: 1199, month: 4, day: 27 },
  { name: "建仁", ruby: "けんにん", rubyInitial: "K", year: 1201, month: 2, day: 13 },
  {
    name: "元久",
    ruby: "げんきゅう",
    rubyInitial: "G",
    year: 1204,
    month: 2,
    day: 20,
  },
  { name: "建永", ruby: "けんえい", rubyInitial: "K", year: 1206, month: 4, day: 27 },
  {
    name: "承元",
    ruby: "じょうげん（しょうげん）",
    rubyInitial: "J",
    year: 1207,
    month: 10,
    day: 25,
  },
  { name: "建暦", ruby: "けんりゃく", rubyInitial: "K", year: 1211, month: 3, day: 9 },
  {
    name: "建保",
    ruby: "けんぽう（けんほう）",
    rubyInitial: "K",
    year: 1213,
    month: 12,
    day: 6,
  },
  {
    name: "承久",
    ruby: "じょうきゅう（しょうきゅう）",
    rubyInitial: "J",
    year: 1219,
    month: 4,
    day: 12,
  },
  {
    name: "貞応",
    ruby: "じょうおう（ていおう）",
    rubyInitial: "J",
    year: 1222,
    month: 4,
    day: 13,
  },
  {
    name: "元仁",
    ruby: "げんにん",
    rubyInitial: "G",
    year: 1224,
    month: 11,
    day: 20,
  },
  { name: "嘉禄", ruby: "かろく", rubyInitial: "K", year: 1225, month: 4, day: 20 },
  {
    name: "安貞",
    ruby: "あんてい",
    rubyInitial: "A",
    year: 1227,
    month: 12,
    day: 10,
  },
  { name: "寛喜", ruby: "かんき", rubyInitial: "K", year: 1229, month: 3, day: 5 },
  {
    name: "貞永",
    ruby: "じょうえい（ていえい）",
    rubyInitial: "J",
    year: 1232,
    month: 4,
    day: 2,
  },
  {
    name: "天福",
    ruby: "てんぷく（てんふく）",
    rubyInitial: "T",
    year: 1233,
    month: 4,
    day: 15,
  },
  {
    name: "文暦",
    ruby: "ぶんりゃく（もんりゃく）",
    rubyInitial: "B",
    year: 1234,
    month: 11,
    day: 5,
  },
  { name: "嘉禎", ruby: "かてい", rubyInitial: "K", year: 1235, month: 9, day: 19 },
  {
    name: "暦仁",
    ruby: "りゃくにん（れきにん）",
    rubyInitial: "R",
    year: 1238,
    month: 11,
    day: 23,
  },
  {
    name: "延応",
    ruby: "えんおう（えんのう）",
    rubyInitial: "E",
    year: 1239,
    month: 2,
    day: 7,
  },
  {
    name: "仁治",
    ruby: "にんじ（にんち）",
    rubyInitial: "N",
    year: 1240,
    month: 7,
    day: 16,
  },
  { name: "寛元", ruby: "かんげん", rubyInitial: "K", year: 1243, month: 2, day: 26 },
  { name: "宝治", ruby: "ほうじ", rubyInitial: "H", year: 1247, month: 2, day: 28 },
  {
    name: "建長",
    ruby: "けんちょう",
    rubyInitial: "K",
    year: 1249,
    month: 3,
    day: 18,
  },
  { name: "康元", ruby: "こうげん", rubyInitial: "K", year: 1256, month: 10, day: 5 },
  { name: "正嘉", ruby: "しょうか", rubyInitial: "S", year: 1257, month: 3, day: 14 },
  {
    name: "正元",
    ruby: "しょうげん",
    rubyInitial: "S",
    year: 1259,
    month: 3,
    day: 26,
  },
  { name: "文応", ruby: "ぶんおう", rubyInitial: "B", year: 1260, month: 4, day: 13 },
  {
    name: "弘長",
    ruby: "こうちょう",
    rubyInitial: "K",
    year: 1261,
    month: 2,
    day: 20,
  },
  { name: "文永", ruby: "ぶんえい", rubyInitial: "B", year: 1264, month: 2, day: 28 },
  { name: "建治", ruby: "けんじ", rubyInitial: "K", year: 1275, month: 4, day: 25 },
  { name: "弘安", ruby: "こうあん", rubyInitial: "K", year: 1278, month: 2, day: 29 },
  {
    name: "正応",
    ruby: "しょうおう",
    rubyInitial: "S",
    year: 1288,
    month: 4,
    day: 28,
  },
  { name: "永仁", ruby: "えいにん", rubyInitial: "E", year: 1293, month: 8, day: 5 },
  {
    name: "正安",
    ruby: "しょうあん",
    rubyInitial: "S",
    year: 1299,
    month: 4,
    day: 25,
  },
  {
    name: "乾元",
    ruby: "けんげん",
    rubyInitial: "K",
    year: 1302,
    month: 11,
    day: 21,
  },
  { name: "嘉元", ruby: "かげん", rubyInitial: "K", year: 1303, month: 8, day: 5 },
  { name: "徳治", ruby: "とくじ", rubyInitial: "T", year: 1306, month: 12, day: 14 },
  {
    name: "延慶",
    ruby: "えんきょう（えんぎょう）",
    rubyInitial: "E",
    year: 1308,
    month: 10,
    day: 9,
  },
  {
    name: "応長",
    ruby: "おうちょう",
    rubyInitial: "O",
    year: 1311,
    month: 4,
    day: 28,
  },
  { name: "正和", ruby: "しょうわ", rubyInitial: "S", year: 1312, month: 3, day: 20 },
  {
    name: "文保",
    ruby: "ぶんぽう（ぶんほう）",
    rubyInitial: "B",
    year: 1317,
    month: 2,
    day: 3,
  },
  {
    name: "元応",
    ruby: "げんおう（げんのう）",
    rubyInitial: "G",
    year: 1319,
    month: 4,
    day: 28,
  },
  { name: "元亨", ruby: "げんこう", rubyInitial: "G", year: 1321, month: 2, day: 23 },
  {
    name: "正中",
    ruby: "しょうちゅう",
    rubyInitial: "S",
    year: 1324,
    month: 12,
    day: 9,
  },
  { name: "嘉暦", ruby: "かりゃく", rubyInitial: "K", year: 1326, month: 4, day: 26 },
  { name: "元徳", ruby: "げんとく", rubyInitial: "G", year: 1329, month: 8, day: 29 },
  { name: "元弘", ruby: "げんこう", rubyInitial: "G", year: 1331, month: 8, day: 9 },
  {
    name: "正慶",
    ruby: "しょうきょう（しょうけい）",
    rubyInitial: "S",
    year: 1332,
    month: 4,
    day: 28,
  },
  {
    name: "建武",
    ruby: "けんむ（けんぶ）",
    rubyInitial: "K",
    year: 1334,
    month: 1,
    day: 29,
  },
  { name: "延元", ruby: "えんげん", rubyInitial: "E", year: 1336, month: 2, day: 29 },
  {
    name: "暦応",
    ruby: "りゃくおう（れきおう）",
    rubyInitial: "R",
    year: 1338,
    month: 8,
    day: 28,
  },
  { name: "興国", ruby: "こうこく", rubyInitial: "K", year: 1340, month: 4, day: 28 },
  { name: "康永", ruby: "こうえい", rubyInitial: "K", year: 1342, month: 4, day: 27 },
  {
    name: "貞和",
    ruby: "じょうわ（ていわ）",
    rubyInitial: "J",
    year: 1345,
    month: 10,
    day: 21,
  },
  {
    name: "正平",
    ruby: "しょうへい",
    rubyInitial: "S",
    year: 1346,
    month: 12,
    day: 8,
  },
  {
    name: "観応",
    ruby: "かんおう（かんのう）",
    rubyInitial: "K",
    year: 1350,
    month: 2,
    day: 27,
  },
  {
    name: "文和",
    ruby: "ぶんな（ぶんわ）",
    rubyInitial: "B",
    year: 1352,
    month: 9,
    day: 27,
  },
  { name: "延文", ruby: "えんぶん", rubyInitial: "E", year: 1356, month: 3, day: 28 },
  { name: "康安", ruby: "こうあん", rubyInitial: "K", year: 1361, month: 3, day: 29 },
  {
    name: "貞治",
    ruby: "じょうじ（ていじ）",
    rubyInitial: "J",
    year: 1362,
    month: 9,
    day: 23,
  },
  { name: "応安", ruby: "おうあん", rubyInitial: "O", year: 1368, month: 2, day: 18 },
  { name: "建徳", ruby: "けんとく", rubyInitial: "K", year: 1370, month: 7, day: 24 },
  { name: "文中", ruby: "ぶんちゅう", rubyInitial: "B", year: 1372, month: 4, day: 1 },
  { name: "天授", ruby: "てんじゅ", rubyInitial: "T", year: 1375, month: 5, day: 27 },
  { name: "永和", ruby: "えいわ", rubyInitial: "E", year: 1375, month: 2, day: 27 },
  {
    name: "康暦",
    ruby: "こうりゃく",
    rubyInitial: "K",
    year: 1379,
    month: 3,
    day: 22,
  },
  { name: "弘和", ruby: "こうわ", rubyInitial: "K", year: 1381, month: 2, day: 10 },
  { name: "永徳", ruby: "えいとく", rubyInitial: "E", year: 1381, month: 2, day: 24 },
  {
    name: "元中",
    ruby: "げんちゅう",
    rubyInitial: "G",
    year: 1384,
    month: 4,
    day: 28,
  },
  { name: "至徳", ruby: "しとく", rubyInitial: "S", year: 1384, month: 2, day: 27 },
  {
    name: "嘉慶",
    ruby: "かきょう（かけい）",
    rubyInitial: "K",
    year: 1387,
    month: 8,
    day: 23,
  },
  { name: "康応", ruby: "こうおう", rubyInitial: "K", year: 1389, month: 2, day: 9 },
  { name: "明徳", ruby: "めいとく", rubyInitial: "M", year: 1390, month: 3, day: 26 },
  { name: "応永", ruby: "おうえい", rubyInitial: "O", year: 1394, month: 7, day: 5 },
  {
    name: "正長",
    ruby: "しょうちょう",
    rubyInitial: "S",
    year: 1428,
    month: 4,
    day: 27,
  },
  { name: "永享", ruby: "えいきょう", rubyInitial: "E", year: 1429, month: 9, day: 5 },
  {
    name: "嘉吉",
    ruby: "かきつ（かきち）",
    rubyInitial: "K",
    year: 1441,
    month: 2,
    day: 17,
  },
  { name: "文安", ruby: "ぶんあん", rubyInitial: "B", year: 1444, month: 2, day: 5 },
  { name: "宝徳", ruby: "ほうとく", rubyInitial: "H", year: 1449, month: 7, day: 28 },
  {
    name: "享徳",
    ruby: "きょうとく",
    rubyInitial: "K",
    year: 1452,
    month: 7,
    day: 25,
  },
  {
    name: "康正",
    ruby: "こうしょう",
    rubyInitial: "K",
    year: 1455,
    month: 7,
    day: 25,
  },
  {
    name: "長禄",
    ruby: "ちょうろく",
    rubyInitial: "T",
    year: 1457,
    month: 9,
    day: 28,
  },
  {
    name: "寛正",
    ruby: "かんしょう",
    rubyInitial: "K",
    year: 1460,
    month: 12,
    day: 21,
  },
  {
    name: "文正",
    ruby: "ぶんしょう（もんしょう）",
    rubyInitial: "B",
    year: 1466,
    month: 2,
    day: 28,
  },
  { name: "応仁", ruby: "おうにん", rubyInitial: "O", year: 1467, month: 3, day: 5 },
  { name: "文明", ruby: "ぶんめい", rubyInitial: "B", year: 1469, month: 4, day: 28 },
  {
    name: "長享",
    ruby: "ちょうきょう",
    rubyInitial: "T",
    year: 1487,
    month: 7,
    day: 20,
  },
  { name: "延徳", ruby: "えんとく", rubyInitial: "E", year: 1489, month: 8, day: 21 },
  { name: "明応", ruby: "めいおう", rubyInitial: "M", year: 1492, month: 7, day: 19 },
  { name: "文亀", ruby: "ぶんき", rubyInitial: "B", year: 1501, month: 2, day: 29 },
  {
    name: "永正",
    ruby: "えいしょう",
    rubyInitial: "E",
    year: 1504,
    month: 2,
    day: 30,
  },
  { name: "大永", ruby: "だいえい", rubyInitial: "D", year: 1521, month: 8, day: 23 },
  {
    name: "享禄",
    ruby: "きょうろく",
    rubyInitial: "K",
    year: 1528,
    month: 8,
    day: 20,
  },
  { name: "天文", ruby: "てんぶん", rubyInitial: "T", year: 1532, month: 7, day: 29 },
  { name: "弘治", ruby: "こうじ", rubyInitial: "K", year: 1555, month: 10, day: 23 },
  { name: "永禄", ruby: "えいろく", rubyInitial: "E", year: 1558, month: 2, day: 28 },
  { name: "元亀", ruby: "げんき", rubyInitial: "G", year: 1570, month: 4, day: 23 },
  { name: "文禄", ruby: "ぶんろく", rubyInitial: "B", year: 1592, month: 12, day: 8 },
  {
    name: "慶長",
    ruby: "けいちょう（きょうちょう）",
    rubyInitial: "K",
    year: 1596,
    month: 10,
    day: 27,
  },
  { name: "寛永", ruby: "かんえい", rubyInitial: "K", year: 1624, month: 2, day: 30 },
  {
    name: "正保",
    ruby: "しょうほう",
    rubyInitial: "S",
    year: 1644,
    month: 12,
    day: 16,
  },
  { name: "慶安", ruby: "けいあん", rubyInitial: "K", year: 1648, month: 2, day: 15 },
  {
    name: "承応",
    ruby: "じょうおう（しょうおう）",
    rubyInitial: "J",
    year: 1652,
    month: 9,
    day: 18,
  },
  {
    name: "明暦",
    ruby: "めいれき（みょうりゃく）",
    rubyInitial: "M",
    year: 1655,
    month: 4,
    day: 13,
  },
  { name: "万治", ruby: "まんじ", rubyInitial: "M", year: 1658, month: 7, day: 23 },
  { name: "寛文", ruby: "かんぶん", rubyInitial: "K", year: 1661, month: 4, day: 25 },
  { name: "延宝", ruby: "えんぽう", rubyInitial: "E", year: 1673, month: 9, day: 21 },
  { name: "天和", ruby: "てんな", rubyInitial: "T", year: 1681, month: 9, day: 29 },
  {
    name: "貞享",
    ruby: "じょうきょう",
    rubyInitial: "J",
    year: 1684,
    month: 2,
    day: 21,
  },
  { name: "元禄", ruby: "げんろく", rubyInitial: "G", year: 1688, month: 9, day: 30 },
  { name: "宝永", ruby: "ほうえい", rubyInitial: "H", year: 1704, month: 3, day: 13 },
  {
    name: "正徳",
    ruby: "しょうとく",
    rubyInitial: "S",
    year: 1711,
    month: 4,
    day: 25,
  },
  {
    name: "享保",
    ruby: "きょうほう（きょうほ）",
    rubyInitial: "K",
    year: 1716,
    month: 6,
    day: 22,
  },
  { name: "元文", ruby: "げんぶん", rubyInitial: "G", year: 1736, month: 4, day: 28 },
  {
    name: "寛保",
    ruby: "かんぽう（かんほう）",
    rubyInitial: "K",
    year: 1741,
    month: 2,
    day: 27,
  },
  {
    name: "延享",
    ruby: "えんきょう",
    rubyInitial: "E",
    year: 1744,
    month: 2,
    day: 21,
  },
  { name: "寛延", ruby: "かんえん", rubyInitial: "K", year: 1748, month: 7, day: 12 },
  {
    name: "宝暦",
    ruby: "ほうれき（ほうりゃく）",
    rubyInitial: "H",
    year: 1751,
    month: 10,
    day: 27,
  },
  { name: "明和", ruby: "めいわ", rubyInitial: "M", year: 1764, month: 6, day: 2 },
  {
    name: "安永",
    ruby: "あんえい",
    rubyInitial: "A",
    year: 1772,
    month: 11,
    day: 16,
  },
  { name: "天明", ruby: "てんめい", rubyInitial: "T", year: 1781, month: 4, day: 2 },
  { name: "寛政", ruby: "かんせい", rubyInitial: "K", year: 1789, month: 1, day: 25 },
  { name: "享和", ruby: "きょうわ", rubyInitial: "K", year: 1801, month: 2, day: 5 },
  { name: "文化", ruby: "ぶんか", rubyInitial: "B", year: 1804, month: 2, day: 11 },
  { name: "文政", ruby: "ぶんせい", rubyInitial: "B", year: 1818, month: 4, day: 22 },
  {
    name: "天保",
    ruby: "てんぽう（てんほう）",
    rubyInitial: "T",
    year: 1830,
    month: 12,
    day: 10,
  },
  { name: "弘化", ruby: "こうか", rubyInitial: "K", year: 1844, month: 12, day: 2 },
  { name: "嘉永", ruby: "かえい", rubyInitial: "K", year: 1848, month: 2, day: 28 },
  {
    name: "安政",
    ruby: "あんせい",
    rubyInitial: "A",
    year: 1854,
    month: 11,
    day: 27,
  },
  { name: "万延", ruby: "まんえん", rubyInitial: "M", year: 1860, month: 3, day: 18 },
  {
    name: "文久",
    ruby: "ぶんきゅう",
    rubyInitial: "B",
    year: 1861,
    month: 2,
    day: 19,
  },
  { name: "元治", ruby: "げんじ", rubyInitial: "G", year: 1864, month: 2, day: 20 },
  { name: "慶応", ruby: "けいおう", rubyInitial: "K", year: 1865, month: 4, day: 7 },
  { name: "明治", ruby: "めいじ", rubyInitial: "M", year: 1868, month: 9, day: 8 },
  {
    name: "大正",
    ruby: "たいしょう",
    rubyInitial: "T",
    year: 1912,
    month: 7,
    day: 30,
  },
  {
    name: "昭和",
    ruby: "しょうわ",
    rubyInitial: "S",
    year: 1926,
    month: 12,
    day: 25,
  },
  { name: "平成", ruby: "へいせい", rubyInitial: "H", year: 1989, month: 1, day: 8 },
  { name: "令和", ruby: "れいわ", rubyInitial: "R", year: 2019, month: 5, day: 1 },
];
